[versions]
micrometer = "1.9.8"
sba-v2 = "2.7.10"
spring-boot-v2 = "2.7.18"
spring-boot-v3 = "3.3.3"

[libraries]
spotless-plugin = { module = "com.diffplug.spotless:spotless-plugin-gradle", version = "6.25.0" }
spring-boot-v2-bom = { module = "org.springframework.boot:spring-boot-dependencies", version.ref = "spring-boot-v2" }
foojay-resolver-plugin = { module = "org.gradle.toolchains:foojay-resolver", version = "0.8.0" }
release-plugin = { group = "pl.allegro.tech.build", name = "axion-release-plugin", version = "1.18.7" }

[plugins]
graalvm = {id = "org.graalvm.buildtools.native", version = "0.10.2"}
nexus = {id = "io.github.gradle-nexus.publish-plugin", version = "2.0.0"}
spring-boot-v2 = {id = "org.springframework.boot", version.ref = "spring-boot-v2"}
spring-boot-v3 = {id = "org.springframework.boot", version.ref = "spring-boot-v3"}
spring-deps = {id = "io.spring.dependency-management", version = "1.1.6"}